# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3afa5bc40a9939db69d2d9d4fe3c40c7ce695c55430d468c5cc945997ebda480b5b5c7180f5cf7b5d026e571218d0a106d8f7628b856009244b8ca7b22c7ea2

test:
  secret_key_base: 9df2b0cfdd4546a17e8770f75a9f87ab75e1b71621042a72ddb418c89e6f2cc037ecdd80c171f9004acaa604d8f53022503bdd23d19a5007726b3dd66888c565

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
